language: android

jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository

branches:
  only:
  - master

install:
- chmod +x ./gradlew

script: ./gradlew clean assembleDebug

notifications:
  email:
    on_success: change
    on_failure: always
before_install:
  - pwd
  - ls -la
  - chmod +x /.gradlew
sudo: false
